(deriv 3 'x)
(derivative 3 'x)
(newline)
(deriv 'x 'x)
(derivative 'x 'x)
(newline)
(deriv '(+ x 5) 'x)
(derivative '(x + 5) 'x)
(newline)
(deriv '(* 3 x) 'x)
(derivative '(3 * x) 'x)
(newline)
(deriv '(/ (* 2 x) (+ x 3) ) 'x )
(derivative '( ( 2 * x ) / ( x + 3 ) ) 'x )
(newline)
(deriv '(sin (** x 2) ) 'x )
(derivative '(sin (x ** 2)) 'x)
(newline)
(deriv '(cos (+ (* 2 x) 5)) 'x)
(derivative '(cos ( (2 * x) + 5 ) ) 'x)
(newline)
(deriv '(log (** x 2)) 'x)
(derivative '(log (x ** 2)) 'x )
(newline)
(deriv '(exp (** x 3)) 'x)
(derivative '(exp (x ** 3)) 'x )
(newline)
(deriv '(/ (exp (** (+ (* 5 x) 3) 2)) (log (sin (cos x) ) ) ) 'x )
(derivative '( (exp ( ( (5 * x) + 3 ) ** 2) ) / (log (sin (cos x) ) ) ) 'x)
(newline)
(eval-deriv '(/ (exp (** (+ (* 5 x) 3) 2)) (log (sin (cos x) ) ) ) 'x 1 )
(eval-derivative '( (exp ( ( (5 * x) + 3 ) ** 2) ) / (log (sin (cos x) ) ) ) 'x 1 )